### ISSUE TITLE
Publish to Pypi the newer version supporting Jinja2 3.x

### ISSUE THREAD

**Issue by tnarik** [metwork-framework/jinja2_shell_extension#11]
Publish to Pypi the newer version supporting Jinja2 3.x

**Comment by thebaptiste** [comment]
v0.0.5 has been released and published to pypi.
Thank you for your interest

**Comment by thebaptiste** [comment]
...and a release 0.0.6 fixing description

**Comment by tnarik** [comment]
thanks so much!
