### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by Era-Dorta** [metwork-framework/jinja2_shell_extension#13]
The shell commands always fail to execute on windows due to adding the `; exit 0` to the command in this line https://github.com/metwork-framework/jinja2_shell_extension/blob/master/jinja2_shell_extension/__init__.py#L16

**Comment by thebaptiste** [comment]
To replace `; exit 0` by `|| exit 0` would be ok for Windows (and Linux by the way) I think ?

**Comment by Era-Dorta** [comment]
I investigated a bit more. PowerShell supports the `;` operator. The problem is that `subprocess.check_output` runs the command on the CMD instead of on PowerShell. I think adding the powershell binary to the command should fix it but I can't test at the moment. So something like `cmd = "powershell.exe %s ; exit 0" % value `

**Comment by thebaptiste** [comment]
If possible I would like something working for Windows AND Linux. `powershell.exe` will not work on Linux...
Could you test my fix : `cmd = "%s || exit 0"` ? I think it works on the Windows CMD...
If necessary I will test the OS to do for Windows something different from Linux, but only if necessary...

**Comment by thebaptiste** [comment]
I releases 2.1.0 with my fix. Let me know if it's ok for you.
